name = "photography-studio-backend"
main = "src/index.js"
compatibility_date = "2024-12-27"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB"
database_name = "prod-d1-studio"
database_id = "a771f874-6bc7-4c78-b2a5-b881581f5810"

[vars]
JWT_SECRET = "super-secret-jwt-key-change-me"
N8N_WEBHOOK_URL = "https://n8n.zackdev.io/webhook/ab6356f0-e889-4f77-a1ae-8bcfd93254d0"

[site]
bucket = "./public"
